apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: full-production-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:

  # -------------------------------
  # 🔥 Node Alerts
  # -------------------------------
  - name: node-alerts
    rules:

    - alert: NodeDown
      expr: up{job="kubelet"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Node down"
        description: "Node {{ $labels.instance }} is not reachable."

    - alert: HighNodeCPU
      expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage on node {{ $labels.instance }} > 85%"

    - alert: HighNodeMemory
      expr: (node_memory_Active_bytes / node_memory_MemTotal_bytes) * 100 > 90
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Memory usage on node {{ $labels.instance }} > 90%"

    - alert: DiskAlmostFull
      expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Low disk space"
        description: "Disk space on {{ $labels.instance }} < 15%"

  # -------------------------------
  # 🔥 Pod Alerts
  # -------------------------------
  - name: pod-alerts
    rules:

    - alert: PodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 3m
      labels:
        severity: critical
      annotations:
        summary: "Pod CrashLoop"
        description: "Pod {{ $labels.pod }} is restarting frequently."

    - alert: PodNotReady
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod not ready"
        description: "Pod {{ $labels.pod }} is not in ready state."

    - alert: HighPodCPU
      expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[5m])) by (pod) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High pod CPU usage"
        description: "Pod {{ $labels.pod }} CPU > 500m"

    - alert: HighPodMemory
      expr: sum(container_memory_usage_bytes{image!=""}) by (pod) > 500000000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory pod usage"
        description: "Pod {{ $labels.pod }} memory usage > 500MB"

  # -------------------------------
  # 🔥 K8s API Server Alerts
  # -------------------------------
  - name: apiserver-alerts
    rules:

    - alert: APIServerDown
      expr: up{job="apiserver"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "API Server is down"
        description: "Kubernetes API Server is not responding."

    - alert: HighAPILatency
      expr: histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le)) > 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High API Latency"
        description: "Kubernetes API server latency > 1s"

  # -------------------------------
  # 🔥 Prometheus Self-Alerts
  # -------------------------------
  - name: prometheus-alerts
    rules:

    - alert: PrometheusTargetMissing
      expr: up == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Prometheus target missing"
        description: "A target is down: {{ $labels.instance }}"

    - alert: PrometheusTooManyRestarts
      expr: changes(process_start_time_seconds[10m]) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Prometheus restarts too often"
        description: "Prometheus restarted more than twice in 10 minutes."

  # -------------------------------
  # 🔥 Application Alerts
  # -------------------------------
  - name: app-alerts
    rules:

    - alert: AppDown
      expr: probe_success{job="blackbox"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Application down"
        description: "Application endpoint {{ $labels.instance }} is not reachable."

